name: if-actions

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "running tests"

  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - run: echo "building app"

  # runs only for pull requests
  pr-check:
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'pull_request'
    steps:
      - run: echo "Running security check"

  # runs only on push to main
  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - run: echo "deploying to production from main"